### ISSUE TITLE
WP-CLI Not Included

### ISSUE THREAD

**Issue by Basilakis** [flywp/local-wp-docker#1]
@tareq1988 community is asking for WP-CLI in this docker image, can u please include?

**Comment by tareq1988** [comment]
Yes, we already include wp-cli in the docker image.

**Comment by Basilakis** [comment]
Hm, got feedback from community that they couldn't load it

**Comment by tareq1988** [comment]
You need to execute like this:

```bash
docker compose exec php wp plugin list
```

<img width="992" alt="image" src="https://github.com/flywp/local-wp-docker/assets/153669/b44c03a9-c16d-4821-9628-2ee2e70812c6">
